
-- Tiny College Database (DDL Script)


CREATE DATABASE IF NOT EXISTS TinyCollege;
USE TinyCollege;

-- Table 1: PROFESSOR
CREATE TABLE PROFESSOR (
    PROF_NUM        INT             NOT NULL,
    PROF_SPECIALTY  VARCHAR(50),
    PROF_RANK       VARCHAR(30),
    PROF_LNAME      VARCHAR(30)     NOT NULL,
    PROF_FNAME      VARCHAR(30)     NOT NULL,
    PROF_INITIAL    CHAR(1),
    PROF_EMAIL      VARCHAR(100),
    DEPT_CODE       CHAR(10),
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (PROF_NUM)
);

-- Table 2: SCHOOL
CREATE TABLE SCHOOL (
    SCHOOL_CODE     CHAR(10)        NOT NULL,
    SCHOOL_NAME     VARCHAR(50)     NOT NULL,
    PROF_NUM        INT,
    CONSTRAINT PK_SCHOOL PRIMARY KEY (SCHOOL_CODE),
    CONSTRAINT FK_SCHOOL_PROF FOREIGN KEY (PROF_NUM) REFERENCES PROFESSOR(PROF_NUM)
);

-- Table 3: DEPARTMENT
CREATE TABLE DEPARTMENT (
    DEPT_CODE       CHAR(10)        NOT NULL,
    DEPT_NAME       VARCHAR(50)     NOT NULL,
    SCHOOL_CODE     CHAR(10)        NOT NULL,
    PROF_NUM        INT,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_CODE),
    CONSTRAINT FK_DEPT_SCHOOL FOREIGN KEY (SCHOOL_CODE) REFERENCES SCHOOL(SCHOOL_CODE),
    CONSTRAINT FK_DEPT_PROF FOREIGN KEY (PROF_NUM) REFERENCES PROFESSOR(PROF_NUM)
);

-- Now add FK from PROFESSOR to DEPARTMENT (added after DEPARTMENT exists)
ALTER TABLE PROFESSOR
    ADD CONSTRAINT FK_PROF_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE);

-- Table 4: COURSE
CREATE TABLE COURSE (
    CRS_CODE        CHAR(10)        NOT NULL,
    CRS_TITLE       VARCHAR(100)    NOT NULL,
    CRS_DESCRIPTION VARCHAR(255),
    CRS_CREDIT      INT,
    DEPT_CODE       CHAR(10)        NOT NULL,
    CONSTRAINT PK_COURSE PRIMARY KEY (CRS_CODE),
    CONSTRAINT FK_COURSE_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE)
);

-- Table 5: BUILDING
CREATE TABLE BUILDING (
    BLDG_CODE       CHAR(10)        NOT NULL,
    BLDG_NAME       VARCHAR(50)     NOT NULL,
    BLDG_LOCATION   VARCHAR(100),
    CONSTRAINT PK_BUILDING PRIMARY KEY (BLDG_CODE)
);

-- Table 6: ROOM
CREATE TABLE ROOM (
    ROOM_CODE       CHAR(10)        NOT NULL,
    ROOM_TYPE       VARCHAR(30),
    BLDG_CODE       CHAR(10)        NOT NULL,
    CONSTRAINT PK_ROOM PRIMARY KEY (ROOM_CODE),
    CONSTRAINT FK_ROOM_BLDG FOREIGN KEY (BLDG_CODE) REFERENCES BUILDING(BLDG_CODE)
);

-- Table 7: CLASS
CREATE TABLE CLASS (
    CLASS_CODE      CHAR(10)        NOT NULL,
    CLASS_SECTION   VARCHAR(10),
    CLASS_TIME      VARCHAR(30),
    CRS_CODE        CHAR(10)        NOT NULL,
    PROF_NUM        INT,
    ROOM_CODE       CHAR(10),
    CONSTRAINT PK_CLASS PRIMARY KEY (CLASS_CODE),
    CONSTRAINT FK_CLASS_COURSE FOREIGN KEY (CRS_CODE) REFERENCES COURSE(CRS_CODE),
    CONSTRAINT FK_CLASS_PROF FOREIGN KEY (PROF_NUM) REFERENCES PROFESSOR(PROF_NUM),
    CONSTRAINT FK_CLASS_ROOM FOREIGN KEY (ROOM_CODE) REFERENCES ROOM(ROOM_CODE)
);

-- Table 8: STUDENT
CREATE TABLE STUDENT (
    STU_NUM         INT             NOT NULL,
    STU_LNAME       VARCHAR(30)     NOT NULL,
    STU_FNAME       VARCHAR(30)     NOT NULL,
    STU_INITIAL     CHAR(1),
    STU_EMAIL       VARCHAR(100),
    DEPT_CODE       CHAR(10),
    PROF_NUM        INT,
    CONSTRAINT PK_STUDENT PRIMARY KEY (STU_NUM),
    CONSTRAINT FK_STU_DEPT FOREIGN KEY (DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE),
    CONSTRAINT FK_STU_PROF FOREIGN KEY (PROF_NUM) REFERENCES PROFESSOR(PROF_NUM)
);

-- Table 9: ENROLL
CREATE TABLE ENROLL (
    STU_NUM         INT             NOT NULL,
    CLASS_CODE      CHAR(10)        NOT NULL,
    ENROLL_DATE     DATE,
    ENROLL_GRADE    CHAR(2),
    CONSTRAINT PK_ENROLL PRIMARY KEY (STU_NUM, CLASS_CODE),
    CONSTRAINT FK_ENROLL_STU FOREIGN KEY (STU_NUM) REFERENCES STUDENT(STU_NUM),
    CONSTRAINT FK_ENROLL_CLASS FOREIGN KEY (CLASS_CODE) REFERENCES CLASS(CLASS_CODE)
);